# Generated by Django 4.2 on 2024-05-29 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_audiosystem_laptop_tv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('kind', models.CharField(max_length=50)),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Gadjet',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('kind', models.CharField(max_length=50)),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('kind', models.CharField(max_length=50)),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Washing_machine',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('kind', models.CharField(max_length=50)),
            ],
            bases=('shop.product',),
        ),
        migrations.RenameField(
            model_name='audiosystem',
            old_name='connectivity',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='processor',
            new_name='kind',
        ),
        migrations.RemoveField(
            model_name='audiosystem',
            name='power_output',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='storage',
        ),
    ]
