# Generated by Django 4.2 on 2024-05-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_computer_gadjet_refrigerator_washing_machine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airfryer',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('kind', models.CharField(max_length=50)),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Blender',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('kind', models.CharField(max_length=50)),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Coffee_maker',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('kind', models.CharField(max_length=50)),
            ],
            bases=('shop.product',),
        ),
    ]
