# Generated by Django 4.2 on 2024-06-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_airfryer_blender_coffee_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosystem',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
