# Generated by Django 4.2 on 2024-06-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_audiosystem_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiosystem',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
